### ISSUE TITLE
Calculate confidences

### ISSUE THREAD

**Issue by erikrtn** [erikrtn/bmed8813#47]

**Comment by mobatusi** [comment]
updated confidence function pushed. Complete

**Comment by erikrtn** [comment]
Gotta make some changes to the algorithm; re-opening and will add notes here. Good start though @mobatusi.

**Comment by erikrtn** [comment]
https://github.com/erikrtn/bmed8813/commit/5ecf068d71d3df21e5ba72f82baa866ed9b25e1b
